# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyVehicleTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.CharField(max_length=100, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('estimated_travel_time', models.CharField(max_length=50, null=True)),
                ('actual_time_taken', models.CharField(max_length=50, null=True)),
                ('delay', models.FloatField(null=True)),
                ('km_run', models.CharField(max_length=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Driver')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Task')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.DeviceActivation')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lat_long', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=5, null=True)),
                ('km_covered', models.CharField(max_length=100, null=True)),
                ('current_location', models.CharField(max_length=255, null=True)),
                ('remaining_time', models.CharField(max_length=100, null=True)),
                ('estimated_reach_time', models.CharField(max_length=100, null=True)),
                ('time_lag', models.CharField(max_length=100, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Task')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_task', models.CharField(max_length=10)),
                ('before_time_task', models.CharField(max_length=10)),
                ('on_time_task', models.CharField(max_length=10)),
                ('total_delay_hours', models.CharField(max_length=10)),
                ('delayed_task_percentage', models.CharField(max_length=5)),
                ('vehicle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Vehicle')),
            ],
        ),
    ]
