# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20171105_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_lat_long',
        ),
    ]
