# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Device_ID', models.CharField(max_length=20, null=True)),
                ('DeviceTimeStamp', models.CharField(max_length=35, null=True)),
                ('Longitude', models.CharField(max_length=20, null=True)),
                ('Latitude', models.CharField(max_length=20, null=True)),
                ('Altitude', models.CharField(max_length=10, null=True)),
                ('Angle', models.CharField(max_length=5, null=True)),
                ('Satellite', models.CharField(max_length=5, null=True)),
                ('Speed_kmph', models.CharField(max_length=5, null=True)),
                ('HDOP', models.CharField(max_length=5, null=True)),
                ('Ignition', models.CharField(max_length=5, null=True)),
                ('Country_Code_Geonames', models.CharField(max_length=5, null=True)),
                ('Virtual_GPS_Odometer', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name_plural': 'Device Data',
            },
        ),
    ]
