# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
