# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_driver_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceactivation',
            name='active',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
