# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20171130_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='assign_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.DeviceActivation'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='select_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Task'),
        ),
    ]
